### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "kabir@rogue.com",
  "password": "secret123",
  "fullName": "Mohammed Kabir Kayode"
}

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "admin@vidacore.com",
  "password": "Vidacore123",
  "fullName": "Bambina Blessing"
}

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "lahobambi@rogue.com",
  "password": "loverbirds",
  "fullName": "laho bambina"
}

### Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "identifier": "kabir@rogue.com",
  "password": "secret123"
}

### Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "identifier": "tife223@gmail.com",
  "password": "12346"
}

### Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "identifier": "lahobambi@rogue.com",
  "password": "loverbirds"
}

### Login with staff ID
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "identifier": "EMP001",
  "password": "secret123"
}

### Login - wrong password
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "identifier": "kabir@rogue.com",
  "password": "wrong"
}

### Me - with cookie
GET http://localhost:3000/auth/me

### Me - tampered token
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.XXXXX.YYYYY

