### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "kabir@rogue.com",
  "password": "secret123",
  "fullName": "Mohammed Kabir Kayode"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "kabir@rogue.com",
  "password": "secret"
}